export const staffUi = {
  staffList: 'ユーザー一覧',
  search: '検索',
  addStaff: 'ユーザー追加',
  building: '建物',
  status: '状態',
  placeholderStatus: '状態を選択してください。',
  onGoing: '有効',
  printQRCode: 'QRコード発行',
  updateInfomation: '編集',
  delete: '削除',
  profileImage: 'プロフィール画像',
  upload: 'アップロード',
  fullName: '名前',
  placeholderName: '名前を入力してください。',
  fullNameKatakana: '名前カナ',
  placeholderNameKatakana: '名前カナを入力してください。',
  userName: 'ユーザー名',
  placeholderUserName: 'ユーザー名を入力してください。',
  phone: '電話番号',
  placeholderPhone: '電話番号を入力してください。',
  email: 'メールアドレス',
  placeholderEmail: 'メールアドレスを入力してください。',
  address1: '住所 1',
  address2: '住所 2',
  placeholderAddress: '住所を入力してください。',
  postalCode: '郵便番号',
  placeholderPostalCode: '郵便番号を入力してください。',
  assignBuilding: '担当する建物設定',
  placeholderAssignBuilding: '建物を選択してください。',
  cancel: 'キャンセル',
  save: '確定',
  dowload: 'ダウンロード',
  print: '印刷',
  active: '有効',
  inactive: '無効',
}
