export const meterUi = {
  meterlist: 'メーター一覧',
  importCSV: 'CSV取り込み',
  search: '検索',
  building: '建物',
  year: '年',
  month: '月',
  staff: '作業者',
  meterID: 'メーターID',
  itemName: '項目名',
  time: '',
  number: '',
  action: '',
  printQR: 'QRコード印刷',
  createQR: 'QRコード発行',
  dowload: 'ダウンロード',
  meterHistory: '検針履歴',
  firstNumber: '前回指針数',
  lastNumber: '今回指針数',
  total: '利用量',
  image: '画像',
  showHistory: ' 検針履歴',
}
